Proj 1 vector operations
krveronika/made-cpp-2020-hw pull request #3
Opened 2020-10-05 21:14 UTC by krveronika

2020-10-16 18:17 UTC, SweetWeakness requested changes

2020-10-16 18:17 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +    std::vector<double> res;
отступ - 2 пробела

2020-10-16 18:17 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +{
кодстайл - скобка на строке выше и перед ней должен быть пробел (дальше аналогично)

2020-10-16 18:17 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +        res.push_back(v1[i] + v2[i]);
создавайте вектор определенной размерности и приравнивайте его элементы (без пушбеков, в дальнейших операторах аналогично)

2020-10-16 18:17 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +}
1) зачем возвращать константный вектор?
2) работаем в интах - зачем лонг лонг?

2020-10-16 18:17 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +}
аналогично

2020-10-16 18:17 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +    res.push_back((long long)(v1[0]) * v2[1] - (long long)(v1[1]) * v2[0]);
аналогично, это же все в интах

2020-10-16 18:17 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +    {
везде надо ставить скобки на строчке выше

2020-10-16 18:17 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +        ++first;
можно просто пройтись for до середины вектора

2020-10-24 11:52 UTC, krveronika commented on vector_operations/src/vector_ops.h
> +}
была идея, что при операциях возможен выход за границы int

2020-10-29 15:40 UTC, merged