Proj 4 functional
krveronika/made-cpp-2020-hw pull request #6
Opened 2020-12-01 20:05 UTC by krveronika

2020-12-02 08:24 UTC, Costello1329 requested changes

2020-12-02 08:24 UTC, Costello1329 commented on proj_4_functional/src/compose.h
> +struct Composer {
Не используйте функтор.
Ваш compose должен работать только над std::function.
Строгая проверка типов... Юзайте синтаксис std::function<R(T)>
Никаких static_assert, ошибка должна возникать на этапе разрешения шаблонной перегрузки функции compose

2020-12-03 22:18 UTC, krveronika commented
compose переписала полностью

2020-12-04 06:59 UTC, Costello1329 approved these changes

2020-12-04 06:59 UTC, Costello1329 commented on proj_4_functional/src/compose.h
> +auto compose(std::function<A(B)> f, std::function<B(C)> g, Args &&... args) {
откуда у args взялась rvalue-ссылка 0.0 ?

2020-12-04 06:59 UTC, Costello1329 commented on proj_4_functional/src/compose.h
> +auto compose(std::function<A(B)> f, std::function<B(C)> g, Args &&... args) {
ну ладно, не страшно, за 8 баллов я вмерджу

2020-12-04 06:59 UTC, merged